name: Build and Deploy Logic App to QA. 

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    
jobs:
  logic_app_build: 
    name: Build QA
    runs-on: ubuntu-latest
    environment: 
      name: QA
    steps: 
    - name: Checkout
      uses: actions/checkout@v1
    - name: Package logic
      run: (cd logic-apps; mkdir -p ../build-art; zip -r ../build-art/logic.zip .)
    - name: Upload app zip package
      uses: actions/upload-artifact@v2
      with:
        name: logic
        path: ./build-art/
        retention-days: 1 

  logic_app_deploy_dev: 
    name: Deploy QA 
    runs-on: ubuntu-latest
    needs: [logic_app_build]
    environment: 
      name: QA
    
    steps: 
    - name: Checkout
      uses: actions/checkout@v1    

    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
    - uses: actions/download-artifact@master
      with:
        name: logic
        path: ./build-art/

    - name: Get publish Profile
      id: publishprofile
      uses: azure/powershell@v1

      with:
        inlineScript: |
          $profile = Get-AzWebAppPublishingProfile `
              -ResourceGroupName ${{vars.AZURE_RESOURCE_GROUP}} `
              -Name ${{vars.LOGIC_APP_NAME}} 
          $profile = $profile.Replace("`r", "").Replace("`n", "")
          Write-Output "::set-output name=profile::$profile"
        azPSVersion: latest

    - name: Deploy to Azure Logic App
      uses: Azure/functions-action@v1.3.1
      id: la
      with:
        app-name: ${{vars.LOGIC_APP_NAME}}
        package: './build-art/logic.zip'
        publish-profile: ${{steps.publishprofile.outputs.profile}}

    - name: Swap parameter files 
      id: params
      uses: azure/powershell@v1
      with:
        inlineScript: |
          az functionapp deploy --resource-group ${{vars.AZURE_RESOURCE_GROUP}} --name ${{vars.LOGIC_APP_NAME}} --src-path  logic-apps/azure.parameters.json --type static --target-path parameters.json
        azPSVersion: latest
