name: Build and Deploy Logic App. 

env:
  RG: 'ais-devops-mp-dev-rg'
  LANAME: 'ais-devops-mp-dev-la'

on:
  workflow_dispatch:
    # Trigger the workflow every time the infrastructure build workflow ran to completion
  workflow_run:
    workflows:
      - Logic App Infrastructure as Code Pipeline.
    types:
      - completed
  # Triggers when Logic Apps workflow logic has changed  
  push:
    paths:
      - "logic/**"
      - ".github/workflows/logicapp_deploy.yml"

jobs:
  logic_app_build: 
    name: Build 
    runs-on: ubuntu-latest
    environment: 
      name: Dev
    steps: 
    - name: Checkout
      uses: actions/checkout@v1
    - name: Package logic
      run: (cd logic-apps; mkdir -p ../build-art; zip -r ../build-art/logic.zip .)
    - name: Upload app zip package
      uses: actions/upload-artifact@v2
      with:
        name: logic
        path: ./build-art/
        retention-days: 1 

  logic_app_deploy_dev: 
    name: Deploy Dev 
    runs-on: ubuntu-latest
    needs: [logic_app_build]
    environment: 
      name: Dev
    
    steps: 
    - name: Checkout
      uses: actions/checkout@v1    

    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
    - uses: actions/download-artifact@master
      with:
        name: logic
        path: ./build-art/

    - name: Get publish Profile
      id: publishprofile
      uses: azure/powershell@v1

      with:
        inlineScript: |
          $profile = Get-AzWebAppPublishingProfile `
              -ResourceGroupName ais-devops-mp-dev-la `
              -Name ${{ env.LANAME }}
          $profile = $profile.Replace("`r", "").Replace("`n", "")
          Write-Output "::set-output name=profile::$profile"
        azPSVersion: latest

    - name: Deploy to Azure Logic App
      uses: Azure/functions-action@v1.3.1
      id: la
      with:
        app-name: ${{env.RG}}
        package: './build-art/logic.zip'
        publish-profile: ${{steps.publishprofile.outputs.profile}}

    - name: Swap parameter files 
      id: params
      uses: azure/powershell@v1
      with:
        inlineScript: |
          az functionapp deploy --resource-group ${{ env.RG }} --name ${{ env.LANAME }} --src-path  logic-apps/azure.parameters.json --type static --target-path parameters.json
        azPSVersion: latest
